### PR TITLE
Use default value instead of (type here)

### PR DESCRIPTION
**Pull request by FranklinWaller**

### CODE REVIEW

**Review by jrop — CHANGES_REQUESTED** [review]
Good catch.  Could you change it to `defaultValue || '(type here)'`?  That way if no default value is provided it falls back to a string.

**Comment by FranklinWaller** [comment]
I would recommend against that since the reason i did this was so i could use an empty string as a prefilled input. (Since the user has to remove the text inside the input before actually typing)

**Comment by jrop** [comment]
Okay then how about `typeof defaultValue == undefined ? '(type here)' : defaultValue`

**Comment by FranklinWaller** [comment]
Is there a reason for using '(type here)'? IMO it seems kinda unnecessary and only annoying for the end user. 😬

**Comment by jrop** [comment]
@FranklinWaller I've been thinking about this, and the purpose of this library is to mimic the `alert/prompt/confirm` dialogs that are builtin to browsers.  In that context, I think you are right: in most implementations, no default text is set (it is blank).

**Comment by jrop** [comment]
@FranklinWaller published as v1.3.0:

https://www.npmjs.com/package/material-ui-dialogs

**Pull request merged**
